### ISSUE TITLE
feat: Initialize Frontend for the Project

### ISSUE THREAD

**Issue by soorya-u** [soorya-u/Scholar-Sync#1]
#  Initialize Frontend for the Project

## TODO

- [ ] Initialize React+Vite Project
- [ ] Add Tailwind
- [ ] Add Tanstack Router
- [ ] Add Apollo GraphQL
