### ISSUE TITLE
Upgrade SurrealDB

### ISSUE THREAD

**Issue by soorya-u** [soorya-u/Scholar-Sync#75]
## TODO

- [x] Bump SurrealDB version to 2.0
- [x] Update to Newer SDK Version
- [x] Update the Schema of the Database
- [x] Rewrite all the Functions of Database
